unique_ids:
  assets:
    standard-page.html: VLSODJL2KT25UZ2ZCDQZIUCWHKUM6PFI
    theme.css: SF6U4HA5GDXGMGISSADX4AOFKBX5OW5W
  forms:
    FeedbackFormForNothing: UTGCQBIKJ2HGXKKR6QKUIAO6A7USQIZ7
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: '1780920862089887603309576.5452'
